# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default=6, upload_to=b'gallery/'),
            preserve_default=False,
        ),
    ]
